### ISSUE TITLE
[Anon] Bug report: Battlegroup.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/adeptus-titanicus#256] opened 2023-03-20 01:12 UTC
**File:** Battlegroup.catz

**BattleScribe version:** 9.79.20

**Platform:** Windows

**Dropbox:** Yes

**Description:** Legio Venator is unable exchange a Warlord for a Reaver. I've checked in multiple maniples and its the same across the board.

**Comment by Sorakamiii** [comment] 2023-03-20 01:14
Leaving a comment with my account so i can see updates

**Comment by MoDLegion** [comment] 2023-03-26 14:01
Closing this one as it's a duplicate of #257

**Closed by MoDLegion** 2023-03-26 14:01 UTC
Labels: duplicate
